# The cluster half of the foundation pair.
#
# On the four public clouds a foundation calls the cloud's own API to build a
# cluster. On the private cloud that API is Kubernetes: NKP manages workload
# clusters with Cluster API, so "create a cluster" is "apply a set of objects
# to the management cluster", and "get its credentials" is "read the Secret
# Cluster API wrote next to them".
#
#   nkp create cluster nutanix … --dry-run -o yaml   (once, by hand)
#          │
#          ▼
#   var.cluster_manifests_dir ──apply──▶ management cluster
#          Cluster / NutanixCluster / KubeadmControlPlane / MachineDeployment
#          │
#          ▼
#   Secret <cluster>-kubeconfig ──read──▶ the kubernetes and helm providers
#
# The manifests are generated by the NKP CLI rather than written here on
# purpose: the shape of an NKP cluster (its Cluster API contract version, the
# addons NKP attaches to it, the Prism Central credential Secret it references)
# belongs to the product, and a hand-rolled copy of it would drift from
# whatever `nkp create cluster` produces for the version in use.
#
# Leaving var.cluster_manifests_dir empty — the default, and what CI uses —
# creates nothing and attaches to a cluster NKP already manages. Both paths end
# at the same kubeconfig Secret, so nothing below this point knows which was
# taken.
locals {
  cluster_manifest_files = var.cluster_manifests_dir == "" ? [] : tolist(fileset(var.cluster_manifests_dir, "*.{yaml,yml}"))

  # One Terraform resource per YAML document, keyed by what identifies the
  # object, so re-generating the manifests updates objects in place instead of
  # renumbering a list and replacing the cluster.
  cluster_manifests = {
    for doc in flatten([
      for f in local.cluster_manifest_files : [
        for d in split("\n---", file("${var.cluster_manifests_dir}/${f}")) : yamldecode(d)
        if trimspace(d) != "" && trimspace(d) != "---"
      ]
    ]) : "${doc.kind}/${try(doc.metadata.namespace, "cluster-scoped")}/${doc.metadata.name}" => doc
  }
}

resource "kubernetes_manifest" "cluster" {
  for_each = local.cluster_manifests
  provider = kubernetes.nkp

  manifest = each.value
}

# The credentials of whatever cluster the two paths above ended at. The
# depends_on is what makes a cold apply work: without it the kubeconfig Secret
# would be read during plan, before Cluster API has written it.
module "cluster" {
  source = "../../modules/nkp-cluster-access"

  providers = { kubernetes = kubernetes.nkp }

  cluster_name      = local.cluster_name
  cluster_namespace = var.cluster_namespace

  depends_on = [kubernetes_manifest.cluster]
}
