# Installs the Portainer Edge Agent on one cluster, so the Portainer server on
# the AKS hub can manage it.
#
# "Edge", not the standard agent, because of the direction of the connection.
# A standard agent is something the server dials into, which on EKS, GKE and
# OKE would mean publishing a cluster-admin API on each of them and pointing
# the hub at it. An Edge Agent dials *out*: it polls the Portainer URL over
# HTTPS and, when an operator opens the environment, opens a reverse tunnel
# back to the same host. Nothing has to be reachable from outside the spoke,
# and the credential is one Edge key that the server can revoke by deleting
# the environment.
#
#   spoke cluster                        AKS hub (foundations/azure)
#   ─────────────────────────            ─────────────────────────────────
#   Deployment portainer-agent
#     EDGE_ID   (ConfigMap)  ──poll──▶   https://portainer.onek8s.lol
#     EDGE_KEY  (Secret)     ──tunnel─▶  portainer.onek8s.lol:8000
#     ServiceAccount + ClusterRoleBinding
#
# The manifest this builds is Portainer's own published Edge Agent manifest for
# Kubernetes, as Terraform resources: same object names, same environment
# variables, same headless Service (the agent uses it to find its peers when
# it is scaled out).
locals {
  labels = merge({
    "app"                          = "portainer-agent"
    "app.kubernetes.io/name"       = "portainer-agent"
    "app.kubernetes.io/managed-by" = "terraform"
    "app.kubernetes.io/part-of"    = "onek8s"
    "onek8s.io/cloud"              = var.cloud
    "onek8s.io/environment"        = var.environment
  }, var.labels)

  # Selector labels are immutable on a Deployment, so they are deliberately
  # the single label Portainer's own manifest selects on — nothing that
  # changes when an environment or a cloud is relabelled.
  selector_labels = {
    app = "portainer-agent"
  }

  # Everything the agent reads from its ConfigMap. EDGE_ID identifies the
  # environment to the server and must match the one the server generated;
  # EDGE_INSECURE_POLL exists for a Portainer published with a certificate the
  # agent cannot verify, which is not the case here (the platform wildcard is
  # a real Let's Encrypt certificate) but is the first thing to reach for when
  # an agent will not connect.
  config = merge({
    EDGE                    = "1"
    EDGE_ID                 = var.edge_id
    EDGE_INSECURE_POLL      = var.insecure_poll ? "1" : "0"
    EDGE_INACTIVITY_TIMEOUT = var.inactivity_timeout
    LOG_LEVEL               = var.log_level
  }, var.extra_config)
}

resource "kubernetes_namespace_v1" "this" {
  count = var.create_namespace ? 1 : 0

  metadata {
    name   = var.namespace
    labels = local.labels
  }
}

# --- Identity ----------------------------------------------------------------
# cluster-admin, which is what Portainer's published manifest binds and what
# the product expects: the agent is the operator's hands on this cluster, so
# anything less turns into "Portainer cannot show you X" at some random point
# in the UI. var.cluster_role is the knob for an environment that wants to
# read-only it (bind "view" instead) and accept that.
resource "kubernetes_service_account_v1" "agent" {
  metadata {
    name      = var.service_account_name
    namespace = var.namespace
    labels    = local.labels
  }

  depends_on = [kubernetes_namespace_v1.this]
}

resource "kubernetes_cluster_role_binding_v1" "agent" {
  metadata {
    name   = var.cluster_role_binding_name
    labels = local.labels
  }

  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = var.cluster_role
  }

  subject {
    kind      = "ServiceAccount"
    name      = kubernetes_service_account_v1.agent.metadata[0].name
    namespace = kubernetes_service_account_v1.agent.metadata[0].namespace
  }
}

# --- Registration material ---------------------------------------------------
resource "kubernetes_config_map_v1" "agent" {
  metadata {
    name      = "portainer-agent-edge"
    namespace = var.namespace
    labels    = local.labels
  }

  data = local.config

  depends_on = [kubernetes_namespace_v1.this]
}

# The Edge key is the credential: it encodes the Portainer URL, the tunnel
# address, the tunnel server's fingerprint and this environment's ID, and it is
# what the server checks on every poll. It is generated by the server (the
# portainer/ stack asks for it) and only stored here.
resource "kubernetes_secret_v1" "agent" {
  metadata {
    name      = "portainer-agent-edge-key"
    namespace = var.namespace
    labels    = local.labels
  }

  data = {
    "edge.key" = var.edge_key
  }

  type = "Opaque"

  depends_on = [kubernetes_namespace_v1.this]
}

# --- The agent ---------------------------------------------------------------
# Headless: the agent discovers its own replicas through this Service rather
# than being reached through it. Nothing outside the cluster talks to the
# agent at all.
resource "kubernetes_service_v1" "agent" {
  metadata {
    name      = "portainer-agent"
    namespace = var.namespace
    labels    = local.labels
  }

  spec {
    cluster_ip = "None"
    selector   = local.selector_labels
  }

  depends_on = [kubernetes_namespace_v1.this]
}

resource "kubernetes_deployment_v1" "agent" {
  metadata {
    name      = "portainer-agent"
    namespace = var.namespace
    labels    = local.labels
  }

  spec {
    replicas = 1

    selector {
      match_labels = local.selector_labels
    }

    template {
      metadata {
        labels = merge(local.labels, local.selector_labels)

        # A changed Edge key or EDGE_ID has to restart the agent: both are
        # read at start-up, and neither a ConfigMap nor a Secret update is
        # noticed by a running pod.
        annotations = {
          "onek8s.io/edge-config" = sha256(jsonencode(local.config))
          "onek8s.io/edge-key"    = sha256(var.edge_key)
        }
      }

      spec {
        service_account_name = kubernetes_service_account_v1.agent.metadata[0].name

        container {
          name              = "portainer-agent"
          image             = "${var.agent_image_repository}:${var.agent_version}"
          image_pull_policy = "Always"

          # Everything static comes from the ConfigMap; these three cannot,
          # because they are either per-pod (the pod IP the agent advertises to
          # its peers) or held in a Secret.
          env_from {
            config_map_ref {
              name = kubernetes_config_map_v1.agent.metadata[0].name
            }
          }

          env {
            name = "KUBERNETES_POD_IP"
            value_from {
              field_ref {
                field_path = "status.podIP"
              }
            }
          }

          # The headless Service above, by name: how the agent finds its peers.
          env {
            name  = "AGENT_CLUSTER_ADDR"
            value = kubernetes_service_v1.agent.metadata[0].name
          }

          env {
            name = "EDGE_KEY"
            value_from {
              secret_key_ref {
                name = kubernetes_secret_v1.agent.metadata[0].name
                key  = "edge.key"
              }
            }
          }

          port {
            container_port = 9001
            protocol       = "TCP"
          }

          port {
            container_port = 80
            protocol       = "TCP"
          }

          resources {
            requests = var.resources.requests
            limits   = var.resources.limits
          }
        }
      }
    }
  }

  # Without the binding the agent starts, connects, and then fails every
  # request Portainer makes of it.
  depends_on = [kubernetes_cluster_role_binding_v1.agent]
}
