variable "cloud" {
  description = "Cloud this agent's cluster runs on (azure, aws, gcp, oci). Labels only — the agent itself is identical everywhere."
  type        = string
}

variable "environment" {
  description = "Environment name, applied as the onek8s.io/environment label."
  type        = string
}

variable "edge_id" {
  description = "Portainer Edge ID of the environment this agent registers as. Generated by the Portainer server when the environment is created."
  type        = string
}

variable "edge_key" {
  description = "Portainer Edge key: the credential the agent authenticates with, encoding the Portainer URL, the tunnel address, the tunnel server fingerprint and the environment ID."
  type        = string
  sensitive   = true
}

variable "namespace" {
  description = "Namespace the agent runs in."
  type        = string
  default     = "portainer"
}

variable "create_namespace" {
  description = "Create var.namespace. False when something else owns it already."
  type        = bool
  default     = true
}

variable "service_account_name" {
  description = "ServiceAccount the agent runs as. Portainer's own manifest name, kept so an agent installed by hand and one installed here are the same object."
  type        = string
  default     = "portainer-sa-clusteradmin"
}

variable "cluster_role_binding_name" {
  description = "Name of the ClusterRoleBinding that grants the agent's ServiceAccount var.cluster_role."
  type        = string
  default     = "portainer-crb-clusteradmin"
}

variable "cluster_role" {
  description = "ClusterRole bound to the agent's ServiceAccount. Portainer expects cluster-admin — the agent is how an operator acts on this cluster — and anything narrower means parts of the UI stop working."
  type        = string
  default     = "cluster-admin"
}

variable "agent_image_repository" {
  description = "Container image repository of the Portainer agent."
  type        = string
  default     = "portainer/agent"
}

variable "agent_version" {
  description = "Portainer agent image tag. Keep it in step with the server: the Edge protocol is versioned together with it."
  type        = string
  default     = "2.39.6"
}

variable "insecure_poll" {
  description = "Let the agent poll Portainer without verifying its TLS certificate (EDGE_INSECURE_POLL). Needed only when the server is published with a certificate the agent cannot chain — not the case behind the platform wildcard."
  type        = bool
  default     = false
}

variable "inactivity_timeout" {
  description = "How long the agent keeps its reverse tunnel open with no activity before closing it (EDGE_INACTIVITY_TIMEOUT)."
  type        = string
  default     = "5m"
}

variable "log_level" {
  description = "Agent log level (DEBUG, INFO, WARN, ERROR)."
  type        = string
  default     = "INFO"
}

variable "extra_config" {
  description = "Extra environment variables for the agent, merged into its ConfigMap (and so overriding the defaults set here)."
  type        = map(string)
  default     = {}
}

variable "resources" {
  description = "Resource requests/limits of the agent container."
  type = object({
    requests = optional(map(string), {
      cpu    = "10m"
      memory = "64Mi"
    })
    limits = optional(map(string), {
      memory = "256Mi"
    })
  })
  default = {}
}

variable "labels" {
  description = "Extra labels applied to every object this module creates."
  type        = map(string)
  default     = {}
}
